/**
 * @file keymapandroid.h
 * @brief
 * @author Frederic SCHERMA (frederic.scherma@dreamoverflow.org)
 * @date 2017-12-09
 * @copyright Copyright (c) 2001-2017 Dream Overflow. All rights reserved.
 * @details
 */

#ifndef _O3D_KEYMAPANDROID_H
#define _O3D_KEYMAPANDROID_H

/* ONLY IF O3D_ANDROID IS SELECTED */
#ifdef O3D_ANDROID

#include <android/keycodes.h>

namespace o3d {

// AKEYCODE_SOFT_LEFT
// AKEYCODE_SOFT_RIGHT
// AKEYCODE_CALL
// AKEYCODE_ENDCALL
// AKEYCODE_STAR
// AKEYCODE_POUND
// AKEYCODE_DPAD_UP
// AKEYCODE_DPAD_DOWN
// AKEYCODE_DPAD_LEFT
// AKEYCODE_DPAD_RIGHT
// AKEYCODE_DPAD_CENTER
// AKEYCODE_VOLUME_UP
// AKEYCODE_VOLUME_DOWN
// AKEYCODE_POWER
// AKEYCODE_CAMERA
// AKEYCODE_SYM
// AKEYCODE_EXPLORER
// AKEYCODE_ENVELOPE
// AKEYCODE_BACK
// AKEYCODE_GRAVE
// AKEYCODE_AT
// AKEYCODE_NUM
// AKEYCODE_HOME
// AKEYCODE_HEADSETHOOK
// AKEYCODE_FOCUS
// AKEYCODE_EQUALS
// AKEYCODE_NOTIFICATION
// AKEYCODE_SEARCH
// AKEYCODE_MEDIA_PLAY_PAUSE
// AKEYCODE_MEDIA_STOP
// AKEYCODE_MEDIA_NEXT
// AKEYCODE_MEDIA_PREVIOUS
// AKEYCODE_MEDIA_REWIND
// AKEYCODE_MEDIA_FAST_FORWARD
// AKEYCODE_MUTE
// AKEYCODE_PICTSYMBOLS
// AKEYCODE_SWITCH_CHARSET
// AKEYCODE_FORWARD_DEL
// AKEYCODE_FUNCTION
// AKEYCODE_FORWARD
// AKEYCODE_MEDIA_PLAY
// AKEYCODE_MEDIA_PAUSE
// AKEYCODE_MEDIA_CLOSE
// AKEYCODE_MEDIA_EJECT
// AKEYCODE_MEDIA_RECORD
// AKEYCODE_VOLUME_MUTE
// AKEYCODE_APP_SWITCH
// AKEYCODE_ZOOM_IN
// AKEYCODE_ZOOM_OUT
// AKEYCODE_LANGUAGE_SWITCH
// AKEYCODE_MANNER_MODE
// AKEYCODE_3D_MODE
// AKEYCODE_CONTACTS
// AKEYCODE_CALENDAR
// AKEYCODE_MUSIC
// AKEYCODE_CALCULATOR
// AKEYCODE_ASSIST
// AKEYCODE_BRIGHTNESS_DOWN
// AKEYCODE_BRIGHTNESS_UP
// AKEYCODE_MEDIA_AUDIO_TRACK
// AKEYCODE_PAIRING
// AKEYCODE_MEDIA_TOP_MENU
// AKEYCODE_11
// AKEYCODE_12
// AKEYCODE_VOICE_ASSIST
// AKEYCODE_CUT
// AKEYCODE_COPY
// AKEYCODE_PASTE
// AKEYCODE_SYSTEM_NAVIGATION_UP
// AKEYCODE_SYSTEM_NAVIGATION_DOWN
// AKEYCODE_SYSTEM_NAVIGATION_LEFT
// AKEYCODE_SYSTEM_NAVIGATION_RIGHT
// AKEYCODE_ALL_APPS
// AKEYCODE_MEDIA_SKIP_FORWARD
// AKEYCODE_MEDIA_SKIP_BACKWARD
// AKEYCODE_MEDIA_STEP_FORWARD
// AKEYCODE_MEDIA_STEP_BACKWARD

// Help
// AKEYCODE_HELP
// AKEYCODE_NAVIGATE_PREVIOUS
// AKEYCODE_NAVIGATE_NEXT
// AKEYCODE_NAVIGATE_IN
// AKEYCODE_NAVIGATE_OUT

// Wear
// AKEYCODE_STEM_PRIMARY
// AKEYCODE_STEM_1
// AKEYCODE_STEM_2
// AKEYCODE_STEM_3

// Energy
// AKEYCODE_WAKEUP
// AKEYCODE_SOFT_SLEEP

// AKEYCODE_ZENKAKU_HANKAKU
// AKEYCODE_EISU
// AKEYCODE_MUHENKAN
// AKEYCODE_HENKAN
// AKEYCODE_KATAKANA_HIRAGANA
// AKEYCODE_YEN
// AKEYCODE_RO
// AKEYCODE_KANA

// TV (media)
// AKEYCODE_INFO
// AKEYCODE_CHANNEL_UP
// AKEYCODE_CHANNEL_DOWN
// AKEYCODE_TV
// AKEYCODE_WINDOW
// AKEYCODE_GUIDE
// AKEYCODE_DVR
// AKEYCODE_BOOKMARK
// AKEYCODE_CAPTIONS
// AKEYCODE_SETTINGS
// AKEYCODE_TV_POWER
// AKEYCODE_STB_INPUT
// AKEYCODE_AVR_POWER
// AKEYCODE_AVR_INPUT
// AKEYCODE_PROG_RED
// AKEYCODE_PROG_GREEN
// AKEYCODE_PROG_YELLOW
// AKEYCODE_PROG_BLUE
// AKEYCODE_LAST_CHANNEL
// AKEYCODE_TV_DATA_SERVICE
// AKEYCODE_TV_RADIO_SERVICE
// AKEYCODE_TV_TELETEXT
// AKEYCODE_TV_NUMBER_ENTRY
// AKEYCODE_TV_TERRESTRIAL_ANALOG
// AKEYCODE_TV_TERRESTRIAL_DIGITAL
// ..
// AKEYCODE_TV_TIMER_PROGRAMMING

// GamePad
// AKEYCODE_BUTTON_A
// AKEYCODE_BUTTON_B
// AKEYCODE_BUTTON_C
// AKEYCODE_BUTTON_D
// AKEYCODE_BUTTON_X
// AKEYCODE_BUTTON_Y
// AKEYCODE_BUTTON_Z
// AKEYCODE_BUTTON_L1
// AKEYCODE_BUTTON_R1
// AKEYCODE_BUTTON_L2
// AKEYCODE_BUTTON_R2
// AKEYCODE_BUTTON_THUMBL
// AKEYCODE_BUTTON_THUMBR
// AKEYCODE_BUTTON_START
// AKEYCODE_BUTTON_SELECT
// AKEYCODE_BUTTON_MODE
// AKEYCODE_BUTTON_1 .. AKEYCODE_BUTTON_16

/**
 * @brief Keyboard keys mapping define based on X11 key sym.
 * @date 2005-01-25
 * @author Frederic SCHERMA (frederic.scherma@dreamoverflow.org)
 */
enum VKey
{
    KEY_UNDEFINED      = AKEYCODE_UNKNOWN,

    KEY_BACKSPACE      = AKEYCODE_DEL,
    KEY_TAB            = AKEYCODE_TAB,

    KEY_CLEAR          = AKEYCODE_CLEAR,
    KEY_RETURN         = AKEYCODE_ENTER,

    KEY_PAUSE          = AKEYCODE_BREAK,
    KEY_CAPSLOCK       = AKEYCODE_CAPS_LOCK,

    KEY_ESCAPE         = AKEYCODE_ESCAPE,
    KEY_SPACE          = AKEYCODE_SPACE,
    KEY_PGUP           = AKEYCODE_PAGE_UP,
    KEY_PGDW           = AKEYCODE_PAGE_DOWN,
    KEY_END            = AKEYCODE_MOVE_END,
    KEY_HOME           = AKEYCODE_MOVE_HOME,
    KEY_LEFT           = AKEYCODE_DPAD_UP_LEFT,
    KEY_UP             = AKEYCODE_DPAD_UP_RIGHT,
    KEY_RIGHT          = AKEYCODE_DPAD_DOWN_RIGHT,
    KEY_DOWN           = AKEYCODE_DPAD_DOWN_LEFT,
    KEY_SELECT         = 0,  // Undefined
    KEY_PRINT          = AKEYCODE_SYSRQ,
    KEY_EXECUTE        = 0,
    KEY_SNAPSHOT       = AKEYCODE_SYSRQ,
    KEY_INSERT         = AKEYCODE_INSERT,
    KEY_DELETE         = AKEYCODE_FORWARD_DEL,
    KEY_HELP           = AKEYCODE_HELP,

    KEY_0              = AKEYCODE_0,      // 0-9
    KEY_1              = AKEYCODE_1,
    KEY_2              = AKEYCODE_2,
    KEY_3              = AKEYCODE_3,
    KEY_4              = AKEYCODE_4,
    KEY_5              = AKEYCODE_5,
    KEY_6              = AKEYCODE_6,
    KEY_7              = AKEYCODE_7,
    KEY_8              = AKEYCODE_8,
    KEY_9              = AKEYCODE_9,

    KEY_A              = AKEYCODE_A,     // A-Z
    KEY_B              = AKEYCODE_B,
    KEY_C              = AKEYCODE_C,
    KEY_D              = AKEYCODE_D,
    KEY_E              = AKEYCODE_E,
    KEY_F              = AKEYCODE_F,
    KEY_G              = AKEYCODE_G,
    KEY_H              = AKEYCODE_H,
    KEY_I              = AKEYCODE_I,
    KEY_J              = AKEYCODE_J,
    KEY_K              = AKEYCODE_K,
    KEY_L              = AKEYCODE_L,
    KEY_M              = AKEYCODE_M,
    KEY_N              = AKEYCODE_N,
    KEY_O              = AKEYCODE_O,
    KEY_P              = AKEYCODE_P,
    KEY_Q              = AKEYCODE_Q,
    KEY_R              = AKEYCODE_R,
    KEY_S              = AKEYCODE_S,
    KEY_T              = AKEYCODE_T,
    KEY_U              = AKEYCODE_U,
    KEY_V              = AKEYCODE_V,
    KEY_W              = AKEYCODE_W,
    KEY_X              = AKEYCODE_X,
    KEY_Y              = AKEYCODE_Y,
    KEY_Z              = AKEYCODE_Z,

    KEY_LSUPER         = AKEYCODE_META_LEFT,
    KEY_RSUPER         = AKEYCODE_META_RIGHT,
    KEY_MENU           = AKEYCODE_MENU,

    KEY_SLEEP          = AKEYCODE_SLEEP

    KEY_NUMPAD0        = AKEYCODE_NUMPAD_0,         // numpad 0-9
    KEY_NUMPAD1        = AKEYCODE_NUMPAD_1,
    KEY_NUMPAD2        = AKEYCODE_NUMPAD_2,
    KEY_NUMPAD3        = AKEYCODE_NUMPAD_3,
    KEY_NUMPAD4        = AKEYCODE_NUMPAD_4,
    KEY_NUMPAD5        = AKEYCODE_NUMPAD_5,
    KEY_NUMPAD6        = AKEYCODE_NUMPAD_6,
    KEY_NUMPAD7        = AKEYCODE_NUMPAD_7,
    KEY_NUMPAD8        = AKEYCODE_NUMPAD_8,
    KEY_NUMPAD9        = AKEYCODE_NUMPAD_9,
    KEY_NUMPAD_MULTIPLY= AKEYCODE_NUMPAD_MULTIPLY,
    KEY_NUMPAD_ADD     = AKEYCODE_NUMPAD_ADD,
    KEY_NUMPAD_SEPARATOR= AKEYCODE_NUMPAD_COMMA,
    KEY_NUMPAD_SUBTRACT= AKEYCODE_NUMPAD_SUBTRACT,
    KEY_NUMPAD_DECIMAL = AKEYCODE_NUMPAD_DOT,   // AKEYCODE_NUMPAD_COMMA
    KEY_NUMPAD_DIVIDE  = AKEYCODE_NUMPAD_DIVIDE,
    KEY_NUMPAD_ENTER   = AKEYCODE_NUMPAD_ENTER,
    KEY_NUMPAD_EQUALS  = AKEYCODE_NUMPAD_EQUALS,
    // KEY_NUMPAD_LPAREN  = AKEYCODE_NUMPAD_LEFT_PAREN
    // KEY_NUMPAD_RPAREN  = AKEYCODE_NUMPAD_RIGHT_PAREN

    KEY_F1             = AKEYCODE_F1,         // F1-F24
    KEY_F2             = AKEYCODE_F2,
    KEY_F3             = AKEYCODE_F3,
    KEY_F4             = AKEYCODE_F4,
    KEY_F5             = AKEYCODE_F5,
    KEY_F6             = AKEYCODE_F6,
    KEY_F7             = AKEYCODE_F7,
    KEY_F8             = AKEYCODE_F8,
    KEY_F9             = AKEYCODE_F9,
    KEY_F10            = AKEYCODE_F10,
    KEY_F11            = AKEYCODE_F11,
    KEY_F12            = AKEYCODE_F11,
    KEY_F13            = 0,
    KEY_F14            = 0,
    KEY_F15            = 0,
    KEY_F16            = 0,
    KEY_F17            = 0,
    KEY_F18            = 0,
    KEY_F19            = 0,
    KEY_F20            = 0,
    KEY_F21            = 0,
    KEY_F22            = 0,
    KEY_F23            = 0,
    KEY_F24            = 0,

    KEY_NUMLOCK        = AKEYCODE_NUM_LOCK,
    KEY_SCROLL         = AKEYCODE_SCROLL_LOCK,

    KEY_LSHIFT         = AKEYCODE_SHIFT_LEFT,
    KEY_RSHIFT         = AKEYCODE_SHIFT_RIGHT,
    KEY_LCONTROL       = AKEYCODE_CTRL_LEFT,
    KEY_RCONTROL       = AKEYCODE_CTRL_RIGHT,
    KEY_LALT           = AKEYCODE_ALT_LEFT,
    KEY_RALT           = AKEYCODE_ALT_RIGHT,
    KEY_ALTGR          = AKEYCODE_NUM,

    KEY_SEMICOLON      = AKEYCODE_SEMICOLON,  // ';:' for US
    KEY_PLUS           = AKEYCODE_PLUS,       // '+' or = ??
    KEY_COMMA          = AKEYCODE_COMMA,      // ','
    KEY_MINUS          = AKEYCODE_MINUS,      // '-'
    KEY_PERIOD         = AKEYCODE_PERIOD,     // '.'
    KEY_SLASH          = AKEYCODE_SLASH,      // '/?' for US
    KEY_BACKQUOTE      = AKEYCODE_GRAVE,      // '`~' for US

    KEY_LEFTBRACKET    = AKEYCODE_LEFT_BRACKET,   //  '[{' for US
    KEY_BACKSLASH      = AKEYCODE_BACKSLASH,      //  '\|' for US
    KEY_RIGHTBRACKET   = AKEYCODE_RIGHT_BRACKET,  //  ']}' for US
    KEY_QUOTEDBL       = AKEYCODE_APOSTROPHE,     //  ''"' for US
    KEY_EXCLAIM        = AKEYCODE_AT,             //  '!§'

    KEY_OEM_102         = 0    //  "<>" or "\|" on RT 102-key kbd.
};

} // namespace o3d

#endif // O3D_ANDROID

#endif // _O3D_KEYMAPANDROID_H
